version: '3.8'

services:
  elevate-ui:
    build: elevate/frontend/.
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - elevate/frontend/.env
    develop:
      watch:
        - action: rebuild
          path: elevate/frontend

  elevate-backend:
    build: elevate/backend/.
    ports:
      - '3001:3001'
    depends_on:
      - db
    env_file:
      - elevate/backend/.env
    develop:
      watch:
        - action: rebuild
          path: elevate/backend

  db:
    image: mysql:8.2
    ports:
      - '3306:3306'
    env_file:
      - elevate/backend/.env
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
