version: '3.8'

services:
  elevate-ui:
    build: elevate/frontend/.
    restart: on-failure
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - elevate/frontend/.env
    develop:
      watch:
        - action: rebuild
          path: elevate/frontend

  elevate-backend:
    build: elevate/backend/.
    restart: on-failure
    ports:
      - '3001:3001'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - elevate/backend/.env
    develop:
      watch:
        - action: rebuild
          path: elevate/backend

  banks:
    build: banks-api/.
    restart: on-failure
    ports:
      - '5005:5000'
    develop:
      watch:
        - action: rebuild
          path: banks-api

  db:
    image: mysql:8.2
    ports:
      - '3306:3306'
    env_file:
      - elevate/backend/.env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
