name: elevate pr workflow

on:
  pull_request:
    paths:
      - 'elevate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: lint frontend
        run: |
          cd elevate/frontend
          npm install
          npm run lint

      - name: lint backend
        run: |
          cd elevate/backend
          npm install
          npm run lint
